# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A VACA ON DATA
email: alejandro_vaca0@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
    I'm Alejandro Vaca, 23yo, from Madrid (Spain). I'm currently engaged in a Master's Degree Program in Data Science & Big Data. 
    Previously, I was graduated in Business. I'm also a piano player, love sports and I'm an amateur writer. 
    This last hobby, together with my passion for Data Science & Machine Learning, were the ones that impulsed me to create this blog.
    By writing these pages I intend for others to embrace data as I do, it is directed towards curious minds that want to learn more about different aspects of the world through data. 
    It can tell us much of who we are, how the economy works, and much more. 
    So I invite you to explore this magic reality of us with the use of these new techniques that are launching Artificial Intelligence to the sky. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexvaca0.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alejandro_vaca0
github_username:  alexvaca0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
